# -*- coding: utf-8 -*-
WeaponConfig = {
    "minecraft:bow": {
        "query_name": "l4d2_item",
        "query_value": 15,
        # attack_type "horizontal" - "vertical" | "left" \ "right" /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        # attack query name
        "normal_attack_name": "normal_attack",
        # attack type list() 1-horizontal 2-vertical 3-left 4-right
        # distance_factor 射线的扩大倍数(长度)
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        # normal_attack_range 能往前打多少
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "minecraft:bone": {
        "query_name": "l4d2_item",
        "query_value": 14,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:pitchfork": {
        "query_name": "l4d2_item",
        "query_value": 13,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "vertical",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:nightstick": {
        "query_name": "l4d2_item",
        "query_value": 12,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:machete": {
        "query_name": "l4d2_item",
        "query_value": 11,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:knife": {
        "query_name": "l4d2_item",
        "query_value": 10,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:katana": {
        "query_name": "l4d2_item",
        "query_value": 9,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:golf_club": {
        "query_name": "l4d2_item",
        "query_value": 8,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:frying_pan": {
        "query_name": "l4d2_item",
        "query_value": 7,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:fireaxe": {
        "query_name": "l4d2_item",
        "query_value": 6,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:electric_guitar": {
        "query_name": "l4d2_item",
        "query_value": 5,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:crowbar": {
        "query_name": "l4d2_item",
        "query_value": 4,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:cricket_bat": {
        "query_name": "l4d2_item",
        "query_value": 3,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:chainsaw": {
        "query_name": "l4d2_item",
        "query_value": 2,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "vertical",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    },
    "fgxm:baseball_bat": {
        "query_name": "l4d2_item",
        "query_value": 1,
        # attack_type 1 - 2 | 3 \ 4 /
        # "effect": [{"effect_name":"","effect_level":1,"effect_time":1}],
        "normal_attack_name": "normal_attack",
        "normal_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "left",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)},
                               {"type": "right",  "distance_factor": 1, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "normal_attack_range": 2,
        "normal_damage": 2,
        "normal_damage_time": 0.3,
        "normal_animation_time": 1,
        "normal_can_knock_back": False,
        "normal_knock_back_multiple": 0.5,
        "normal_need_motion": False,
        "normal_motion": (0, 1, 0),
        "normal_attacker_need_forward": False,
        "normal_forward_distant": 0.2,
        "normal_effect": [],

        "heavy_attack_name": "heavy_attack",
        "heavy_attack_type": [{"type": "horizontal",  "distance_factor": 3, "start_xyz_change": (0, 0, 0), "end_xyz_change": (0, 0, 0)}],
        "heavy_attack_range": 2,
        "heavy_damage": 2,
        "heavy_damage_time": 0.3,
        "heavy_animation_time": 2,
        "heavy_can_knock_back": False,
        "heavy_knock_back_multiple": 0.5,
        "heavy_need_motion": False,
        "heavy_motion": (0, 1, 0),
        "heavy_attacker_need_forward": False,
        "heavy_forward_distant": 0.2,
        "heavy_effect": [],
    }
}
